---
# Source: robot-shop/templates/mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
        version: 2.0.14
    spec:
      
      containers:
      - name: mongodb
        image: sysobs/rs-mongodb:2.0.14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
