---
# Source: robot-shop/templates/mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
        version: 2.0.14
    spec:
      
      containers:
      - name: mysql
        image: sysobs/rs-mysql-db:2.0.14
        imagePullPolicy: IfNotPresent
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
