opentracing:
  jaeger:
    service-name: shipping.robot-shop
    enabled: TRUE
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
    enable-b3-propagation: TRUE
    enable-w3c-propagation: TRUE
