# Registry and rpository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: sysobs
  version: latest
  pullPolicy: IfNotPresent

# Alternative payment gateway URL
# Default is https://www.paypal.com
# The alternative payment gateway must return an HTTP 200
payment:
  #gateway: null
  gateway: https://github.com

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

# Storage class to use with redis statefulset.
redis:
  inMemory: true
  storageClassName: standard

ocCreateRoute: false
