apiVersion: apps/v1
{{ if not .Values.redis.inMemory }}
kind: StatefulSet
{{ end }}
{{ if .Values.redis.inMemory }}
kind: Deployment
{{ end }}
metadata:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  {{ if not .Values.redis.inMemory }}
  serviceName: redis
  {{ end }}
  template:
    metadata:
      labels:
        service: redis
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: redis
        image: redis:4.0.6
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6379
        {{ if not .Values.redis.inMemory }}
        volumeMounts:
          - name: data
            mountPath: /mnt/redis
        {{ end }}
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  {{ if not .Values.redis.inMemory }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if not .Values.openshift }}
        storageClassName: {{ .Values.redis.storageClassName }}
        volumeMode: Filesystem
        {{ end }}
        resources:
          requests:
            storage: 1Gi
  {{ end }}
